apiVersion: v1
kind: Namespace
metadata:
  name: kpack
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.25
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
  namespace: kpack
data:
  zap-logger-config: |
    {
      "level": "info",
      "development": false,
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "rfc3339nano",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-image
  namespace: kpack
data:
  image: gcr.io/cf-build-service-public/kpack/build-init@sha256:fb6d8b324e2f041adb4766d65eec7bee884f84b272eb3ecf0a5c739e96a07b33
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-windows-image
  namespace: kpack
data:
  image: gcr.io/cf-build-service-public/kpack/build-init-windows@sha256:e38940a1d2137c8aa5a94368a206cc78a1b54bd6a09a825a66df0f9cc08c8652
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-waiter-image
  namespace: kpack
data:
  image: gcr.io/cf-build-service-public/kpack/build-waiter@sha256:1422962f7a08c701f362fa043fce889bb4537579ce9dea256625a745356812dc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rebase-image
  namespace: kpack
data:
  image: gcr.io/cf-build-service-public/kpack/rebase@sha256:8db2aceeb340f8686db8b603bbec4aec1682e237b514b8ee05a778714ede5938
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lifecycle-image
  namespace: kpack
data:
  image: gcr.io/cf-build-service-public/kpack/lifecycle@sha256:199043ac6fd40f772decb804ca92cdcbb22b76cf8db622761e25c39c2925d3b7
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completion-image
  namespace: kpack
data:
  image: gcr.io/cf-build-service-public/kpack/completion@sha256:591b577d8286f3eb7583660c59990aa3939878dd69dd1a99897e09d2dc962806
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completion-windows-image
  namespace: kpack
data:
  image: gcr.io/cf-build-service-public/kpack/completion-windows@sha256:f3fb747b55278fabe808ba1b8447b30cd6857567b73acb2bad3123afb509d453
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-controller
  namespace: kpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-controller
  template:
    metadata:
      labels:
        app: kpack-controller
        version: 0.13.2
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      priorityClassName: kpack-control-plane
      serviceAccountName: controller
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: controller
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        image: gcr.io/cf-build-service-public/kpack/controller@sha256:c401a8c1d45f9a24d36568a2f202fd78363cb3ed0dddb36b95e7cc65fc6f536c
        env:
        - name: ENABLE_PRIORITY_CLASSES
          value: "false"
        - name: INJECTED_SIDECAR_SUPPORT
          value: "false"
        - name: EXPERIMENTAL_GENERATE_SLSA_ATTESTATION
          value: "false"
        - name: INSECURE_SSH_TRUST_UNKNOWN_HOSTS
          value: "true"
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: kpack.io
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SYSTEM_SERVICE_ACCOUNT
          value: controller
        - name: BUILD_INIT_IMAGE
          valueFrom:
            configMapKeyRef:
              name: build-init-image
              key: image
        - name: BUILD_INIT_WINDOWS_IMAGE
          valueFrom:
            configMapKeyRef:
              name: build-init-windows-image
              key: image
        - name: BUILD_WAITER_IMAGE
          valueFrom:
            configMapKeyRef:
              name: build-waiter-image
              key: image
        - name: REBASE_IMAGE
          valueFrom:
            configMapKeyRef:
              name: rebase-image
              key: image
        - name: COMPLETION_IMAGE
          valueFrom:
            configMapKeyRef:
              name: completion-image
              key: image
        - name: COMPLETION_WINDOWS_IMAGE
          valueFrom:
            configMapKeyRef:
              name: completion-windows-image
              key: image
        resources:
          requests:
            cpu: 20m
            memory: 1Gi
          limits:
            memory: 1Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: kpack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpack-controller-admin
rules:
- apiGroups:
  - kpack.io
  resources:
  - builds
  - builds/status
  - builds/finalizers
  - images
  - images/status
  - images/finalizers
  - builders
  - builders/status
  - buildpacks
  - buildpacks/status
  - clusterbuilders
  - clusterbuilders/status
  - clusterbuildpacks
  - clusterbuildpacks/status
  - clusterstores
  - clusterstores/status
  - clusterstacks
  - clusterstacks/status
  - sourceresolvers
  - sourceresolvers/status
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - pods/log
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kpack-controller-admin-binding
subjects:
- kind: ServiceAccount
  name: controller
  namespace: kpack
roleRef:
  kind: ClusterRole
  name: kpack-controller-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpack-controller-servicebindings-cluster-role
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      servicebinding.io/controller: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kpack-controller-servicebindings-binding
subjects:
- kind: ServiceAccount
  name: controller
  namespace: kpack
roleRef:
  kind: ClusterRole
  name: kpack-controller-servicebindings-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kpack-controller-local-config
  namespace: kpack
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kpack-controller-local-config-binding
  namespace: kpack
subjects:
- kind: ServiceAccount
  name: controller
  namespace: kpack
roleRef:
  kind: Role
  name: kpack-controller-local-config
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kpack-control-plane
value: 10000
globalDefault: false
description: Super High priority class for kpack control plane components
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kpack-build-high-priority
value: 1000
globalDefault: false
description: High priority class for kpack builds triggered by user changes.
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kpack-build-low-priority
value: 1
globalDefault: false
preemptionPolicy: Never
description: Low priority class for kpack builds triggered by operator changes.
---
apiVersion: v1
kind: Service
metadata:
  name: kpack-webhook
  namespace: kpack
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    role: webhook
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: defaults.webhook.kpack.io
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: kpack-webhook
      namespace: kpack
  failurePolicy: Fail
  matchPolicy: Exact
  sideEffects: None
  name: defaults.webhook.kpack.io
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.kpack.io
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: kpack-webhook
      namespace: kpack
  failurePolicy: Fail
  matchPolicy: Exact
  sideEffects: None
  name: validation.webhook.kpack.io
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  namespace: kpack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-webhook
  namespace: kpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-webhook
  template:
    metadata:
      labels:
        app: kpack-webhook
        role: webhook
        version: 0.13.2
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      priorityClassName: kpack-control-plane
      serviceAccountName: webhook
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: webhook
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        image: gcr.io/cf-build-service-public/kpack/webhook@sha256:1064ab5d533f841461eded30980395710b195f36d7e3199e8ef04979d35fa077
        ports:
        - name: https-webhook
          containerPort: 8443
        env:
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: kpack.io
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 200Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook
  namespace: kpack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kpack-webhook-certs-admin
  namespace: kpack
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - webhook-certs
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kpack-webhook-certs-admin-binding
  namespace: kpack
subjects:
- kind: ServiceAccount
  name: webhook
  namespace: kpack
roleRef:
  kind: Role
  name: kpack-webhook-certs-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpack-webhook-mutatingwebhookconfiguration-admin
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  resourceNames:
  - kpack
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - namespaces/finalizers
  verbs:
  - update
  resourceNames:
  - kpack
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  resourceNames:
  - defaults.webhook.kpack.io
  verbs:
  - update
  - delete
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  resourceNames:
  - validation.webhook.kpack.io
  verbs:
  - update
  - delete
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  resourceNames:
  - images.kpack.io
  - builds.kpack.io
  - builders.kpack.io
  - sourceresolvers.kpack.io
  verbs:
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kpack-webhook-certs-mutatingwebhookconfiguration-admin-binding
subjects:
- kind: ServiceAccount
  name: webhook
  namespace: kpack
roleRef:
  kind: ClusterRole
  name: kpack-webhook-mutatingwebhookconfiguration-admin
  apiGroup: rbac.authorization.k8s.io
